# This is a sample build configuration for Python.
# Check our guides at https://confluence.atlassian.com/x/x4UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: python:3.9

pipelines:
  default:
    - step:
        name: Deploy to Heroku
        deployment: production
        caches:
          - pip
        script:
          - apt-get update && apt-get install -y zip curl  # Install zip and curl utilities
          - curl https://cli-assets.heroku.com/install.sh | sh  # Install Heroku CLI
          - echo "$HEROKU_API_KEY" | heroku auth:token  # Authenticate with Heroku
          - pip install --upgrade pip
          - pip install -r requirements.txt
          - mkdir app  # Create the ./app directory as Heroku expects
          - cp -R app.py meal_app requirements.txt app/  # Copy files into the ./app directory
          - tar -czvf app.tar.gz -C app .  # Create a .tar.gz file from the ./app directory
          - pipe: atlassian/heroku-deploy:0.1.1
            variables:
              HEROKU_API_KEY: $HEROKU_API_KEY
              HEROKU_APP_NAME: $HEROKU_APP_NAME
              RECIPE_SEARCH_APP_ID: $RECIPE_SEARCH_APP_ID
              RECIPE_SEARCH_API_KEY: $RECIPE_SEARCH_API_KEY
              ZIP_FILE: "app.tar.gz"  # Specify the .tar.gz file
              WAIT: 'true'
