# This is a sample build configuration for Python.
# Check our guides at https://confluence.atlassian.com/x/x4UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: python:3.9

pipelines:
  default:
    - step:
        name: Deploy to Heroku
        deployment: production
        caches:
          - pip
        script:
          - apt-get update && apt-get install -y zip  # Install zip utility
          - pip install --upgrade pip
          - pip install -r requirements.txt
          - mkdir temp_dir  # Create a temporary directory
          - cp app.py temp_dir/  # Copy app.py to temp_dir
          - cp -r meal_app temp_dir/  # Copy meal_app to temp_dir
          - cd temp_dir  # Navigate to temp_dir
          - zip -r -0 ../app.zip . -x "*.git*" "*.firebase*" "*.pytest_cache*" "*.venv*" "Designs/*" "Research Documentation/*" "*.pdf" "*.docx" "*.png" "*.webp" "tests/*" "__pycache__/*"
          - cd ..  # Go back to the root directory
          - unzip -l app.zip  # List the contents of the ZIP file
          - pipe: atlassian/heroku-deploy:0.1.1
            variables:
              HEROKU_API_KEY: $HEROKU_API_KEY
              HEROKU_APP_NAME: $HEROKU_APP_NAME
              ZIP_FILE: "app.zip"
              WAIT: 'true'





