# This is a sample build configuration for Python.
# Check our guides at https://confluence.atlassian.com/x/x4UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: python:3.9

pipelines:
  default:
    - step:
        name: Deploy to Heroku
        deployment: production
        caches:
          - pip
        script:
          - apt-get update && apt-get install -y zip curl  # Install zip and curl utilities
          - curl https://cli-assets.heroku.com/install.sh | sh  # Install Heroku CLI
          - echo "$HEROKU_API_KEY" | heroku auth:token  # Authenticate with Heroku
          - pip install --upgrade pip
          - pip install -r requirements.txt
          - heroku buildpacks:set heroku/python --app $HEROKU_APP_NAME  # Set the Python buildpack
          - zip -r app.zip app.py meal_app/* requirements.txt -x "*.git*" "*.firebase*" "*.pytest_cache*" "*.venv*" "Designs/*" "Research Documentation/*" "*.pdf" "*.docx" "*.png" "*.webp" "tests/*" "__pycache__/*" -x "*/.*"  # Create zip file
          - du -sh app.zip  # Check the size of the ZIP file
          - unzip -l app.zip  # List contents of the ZIP file for verification
          - pipe: atlassian/heroku-deploy:0.1.1
            variables:
              HEROKU_API_KEY: $HEROKU_API_KEY
              HEROKU_APP_NAME: $HEROKU_APP_NAME
              ZIP_FILE: "app.zip"
              WAIT: 'true'
